/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        layout: {
            animation: 'slide',
            type: 'card'
        },
        items: [
            {
                xtype: 'container',
                title: 'Triggers',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'togglefield',
                        label: 'Position'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Temperature'
                    },
                    {
                        xtype: 'spinnerfield',
                        label: '',
                        stepValue: 1
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Time'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Date'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: '',
                        placeHolder: 'mm/dd/yyyy'
                    },
                    {
                        xtype: 'carousel',
                        flex: 1,
                        direction: 'vertical',
                        items: [
                            {
                                xtype: 'togglefield',
                                label: 'Wifi'
                            },
                            {
                                xtype: 'togglefield',
                                label: 'Headphones'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Actions',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'togglefield',
                        label: 'Email'
                    },
                    {
                        xtype: 'emailfield',
                        label: '',
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Brigthness'
                    },
                    {
                        xtype: 'sliderfield',
                        label: ''
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Perform software actualizations'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Turn on radio'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Turn on alarm'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Record'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'SMS'
                    },
                    {
                        xtype: 'numberfield',
                        label: ''
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Run program'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Play sound'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Sound profile'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Widget Designer',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 345,
                        ui: '',
                        width: 478,
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: 'Text'
                            },
                            {
                                xtype: 'button',
                                text: 'Image'
                            },
                            {
                                xtype: 'button',
                                text: 'Map'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        height: 221,
                        width: 492,
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'label',
                                html: 'canvas area (dropdown)'
                            },
                            {
                                xtype: 'image',
                                height: 201,
                                ui: '',
                                src: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSf1EqdIgnHtVgA3FcMEB3e8uEPwvft4sertRqqlZHX3FSotqL4'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});